# .github/workflows/update-other-repo.yml
name: Update Other Repo on Tag in GA

on:
  push:
    tags:
      - 'ga-client_*'  
  workflow_dispatch: 

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Extract version from tag
        run: |
          TAG=${GITHUB_REF##*/}            # full tag like ga-client_v1.0.1
          VERSION=${TAG##ga-client_}       # strip prefix, leave v1.0.1
          echo "TAG=$TAG"
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Clone target repo
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/zhunan915/augocd.git
          cd augocd
          git checkout main
          git pull -f origin main
          cd frontend/client
          # sed -i 's#v1.0.0#v1.0.1#' frontend-client.yaml
          # sed -i "s#v[0-9]*\.[0-9]*\.[0-9]*#${VERSION}#" frontend-client.yaml
          sed -i "s#client:.*#client:${VERSION}#" frontend-client.yaml
          git config --global user.email "zshuai@dons.usfca.edu"
          git config --global user.name "zhunan915"
          git add frontend-client.yaml
          git commit -m "Update frontend-client.yaml to ${VERSION}"
          git push origin main
          