# .github/workflows/update-other-repo.yml
name: Update Other Repo on Tag in PROD

on:
  push:
    tags:
      - 'ga-posts_*'  
      - 'ga-comments_*'  
      - 'ga-query_*'  
      - 'ga-moderation_*'  
      - 'ga-event-bus_*'  
  workflow_dispatch: 

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Extract service and version from tag
        run: |
          TAG=${GITHUB_REF##*/}  # e.g. ga-event-bus_v1.0.1
          SERVICE=$(echo "$TAG" | sed -E 's/^rc-([^-_]+(-[^-_]+)*)_.*/\1/')   
          VERSION=${TAG#*_} 
          echo "TAG=$TAG"
          echo "SERVICE=$SERVICE"
          echo "VERSION=$VERSION"
          echo "SERVICE=$SERVICE" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Clone target repo
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/zhunan915/augocd.git
          cd augocd
          git checkout main
          git pull -f origin main
          cd backend/${SERVICE}
          # sed -i 's#v1.0.0#v1.0.1#' frontend-client.yaml
          # sed -i "s#v[0-9]*\.[0-9]*\.[0-9]*#${VERSION}#" backend-${SERVICE}.yaml
          sed -i "s#${SERVICE}:.*#${SERVICE}:${VERSION}#" backend-${SERVICE}.yaml
          git config --global user.email "zshuai@dons.usfca.edu"
          git config --global user.name "zhunan915"
          git add backend-${SERVICE}.yaml
          git commit -m "Update backend-${SERVICE}.yaml to ${VERSION}"
          git push origin main
