# .github/workflows/update-other-repo.yml
name: Update Other Repo on Tag in UAT

on:
  push:
    tags:
      - 'rc-posts-*'  
      - 'rc-comments-*'  
      - 'rc-query-*'  
      - 'rc-moderation-*'  
      - 'rc-event-bus-*'  
  workflow_dispatch: 

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Extract service and version from tag
        run: |
          TAG=${GITHUB_REF##*/}  # e.g. rc-event-bus-v1.0.1
          SERVICE=$(echo "$TAG" | sed -E 's/^rc-([^-]+(-[^-]+)*)-.*/\1/')   # gets everything between rc- and -<version>
          VERSION=${TAG#"$SERVICE"-}  # removes service- part to get version
          echo "TAG=$TAG"
          echo "SERVICE=$SERVICE"
          echo "VERSION=$VERSION"
          echo "SERVICE=$SERVICE" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Clone target repo
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/zhunan915/augocd.git
          cd augocd
          git checkout uat
          git pull -f origin uat
          cd backend
          # sed -i 's#v1.0.0#v1.0.1#' frontend-client.yaml
          # sed -i "s#v[0-9]*\.[0-9]*\.[0-9]*#${VERSION}#" backend-${SERVICE}.yaml
          sed -i "s#${SERVICE}:.*#${SERVICE}:${VERSION}#" backend-${SERVICE}.yaml
          git config --global user.email "zshuai@dons.usfca.edu"
          git config --global user.name "zhunan915"
          git add backend-${SERVICE}.yaml
          git commit -m "Update backend-${SERVICE}.yaml to ${VERSION}"
          git push origin uat

          
      - name: Run UAT test for backend service
        run: |
          URL="http://uat.zhunandomain.live/${SERVICE}"
          echo "Running UAT test on: $URL"
          curl --fail --retry 3 --retry-delay 5 "$URL" || (echo "UAT test failed for $SERVICE" && exit 1)

